### ISSUE TITLE
OPERA-SDSVnV-9_1: Manually validate PCM can Retrieve and download of HLS Data Products for the SHORT_NAME= HLSS30 & HLSL30

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#1]
Demonstrate that the PCM system can successfully query CMR for available input products for all PGEs (from current and previous releases), and download them from LP.DAAC to the SDS Input Storage Location (ISL). Do this for different time range selections, including the latest products (to support FWD mode) and some time interval in the past (to support "catch-up" mode).

Verify that the SDS adheres to the external interfaces with the DAACs as specified in the ICD agreement, specifically:
o The SDS identifies its input products by querying the ESDIS CMR (Common Metadata Registry)
o The SDS downloads its input data products using the Cumulus download service deployed at the source DAAC

TestRail link: 
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3351557&group_by=cases:section_id&group_order=asc&group_id=69570

**Comment by LucaCinquini** [comment]
To Do:

o Steps 9 and 11: must have a process to compare the result of the query to a reference output, because simply checking manually is error prone. For example, you can compare versus the same query executed against CMR, or capture the output in files and diff the current and a previous file

o To be more true to the requirement that needs to be tested, change steps 8 and 13 to query only the latest available data, for example for the last 1, 2 or 3 days

**Comment by oddes** [comment]
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3351557&group_by=cases:section_id&group_id=69570&group_order=asc

**Comment by LucaCinquini** [comment]
o Section 2 (query for HLSS30) has both the query for the last 60 minutes of available data, and data for some time interval in the past. Section 3 (query for HLSL30) only has the query for the last 60 minutes - can you please add the query for the some interval in the past?

o Also, in all cases, how do we make sure that the results are correct? At the very least we should compare the number of results from querying CMR and executing the script.

**Comment by oddes** [comment]
Updated:
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3351557

**Comment by LucaCinquini** [comment]
For now, "Response should match", will be implemented by screen. capture and highlighting the number of files.

**Comment by oddes** [comment]
Updated as suggested:
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3351557

**Comment by LucaCinquini** [comment]
Thanks for the corrections, closing.
