### ISSUE TITLE
OPERA-SDS-VnV-1: "Verify Operations begin as planned after CalVal"

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#10]
Requirement: "Demonstrate that system operations will begin within 1 month of the completion of product validation, for each major release"

To do:
o Record the data when CalVal ends (for each PGE)
o Record the data when Operations begin (for the same PGE)

Verify that the difference is <= 1 month

**Comment by oddes** [comment]
Luca, Please review and close the ticket.
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3551345&group_by=cases:title&group_order=asc&group_id=-1

**Comment by LucaCinquini** [comment]
Looks good, closing.
