### ISSUE TITLE
OPERA-SDS-VnV-2: Verify compliance with JPL and NASA Cybersecurity requirements

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#11]
Requirement: "Verify that OPERA SDS has passed the NASA A&A process to obtain the ATO (Authorization To Operate)."

To do:
Simply record the data when ATO is given to OPERA, and provide a link to the official document. The ISO will be notified and will notify everybody else.

**Comment by oddes** [comment]
Luca, Please review the below and close the ticket:
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3816034&group_by=cases:title&group_order=asc&group_id=-1

**Comment by LucaCinquini** [comment]
It seems like Step 1 should be completely removed? The PO.DAAC has nothing to do with this requirement.

**Comment by LucaCinquini** [comment]
Add the requirement description instead.

**Comment by LucaCinquini** [comment]
Never mind, I fixed the issues, closing.
