### ISSUE TITLE
OPERA-SDS-VnV-17: Timed test for retrieval of input products

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#16]
VnV Activity:
"Verify that the SDS can retrieve and ingest input products for all available PGEs (for current and previous releases) automatically within the time allotted by OPERA-SDS-44 and OPERA-SDS-45.
"

**Comment by LucaCinquini** [comment]
OPERA-SDS-44: "The OPERA System shall complete retrieval of new input data products within 9 hours for Forward Processing of non-time-series data products for no less than 90% of all such retrievals."

OPERA-SDS-45: "For Forward Processing of time-series products, the OPERA System shall begin all input retreivals within 9 hours, and complete within 18 hours, measured from when the latest input is available at the DAAC, for no less than 90% of all time-series retrievals."

**Comment by LucaCinquini** [comment]
Suggested Approach for the L3_DSWx_HLS PGE (repeat for each PGE):
o Setup the PGE trigger to query data from the LP.DAAC that was generated in the last 60 minutes
o Verify that all jobs start after the trigger is executed
o Verify that all jobs complete with 9 hours (for the non-time-series) and 18 hours (for the time-series products)
Note: the 90% level is NOT verified during I&T, rather it will be verified during operations on a monthly basis.

**Comment by sjlewis-jpl** [comment]
We want to make sure that these are the jobs for retrieving the data from the DAAC into our system.  This test does not need to actually run the PGEs.

**Comment by LucaCinquini** [comment]
I think you are right - I read it as a requirement on the data processing time but it is indeed on the retrieval of the input only.

**Comment by LucaCinquini** [comment]
Ready to transfer to TestRail.
