### ISSUE TITLE
OPERA-SDSVnV-9_2: Automated retrieval and Ingestion of HLS products

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#2]
Demonstrate that the PCM system can successfully query CMR for available input products for all PGEs (from current and previous releases), and download them from LP.DAAC to the SDS Input Storage Location (ISL). Do this for different time range selections, including the latest products (to support FWD mode) and some time interval in the past (to support "catch-up" mode).

Verify that the SDS adheres to the external interfaces with the DAACs as specified in the ICD agreement, specifically:
o The SDS identifies its input products by querying the ESDIS CMR (Common Metadata Registry)
o The SDS downloads its input data products using the Cumulus download service deployed at the source DAAC

TestRail link: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3718400&group_by=cases:section_id&group_order=asc&group_id=69570

**Comment by LucaCinquini** [comment]
Change title to OPERA-SDSVnV-9_2 to have a consistent convention for all tickets

**Comment by LucaCinquini** [comment]
This ticket involves making sure that the Lambda functions run as timers and check the output data is automatically downloaded to the designated location in the ISL.

**Comment by oddes** [comment]
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3718400&group_by=cases:section_id&group_id=69570&group_order=asc

**Comment by LucaCinquini** [comment]
Step 17: explain a little better:
"Verify that the output products are written in the directory:"

**Comment by oddes** [comment]
Updated to step 17: 
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3718400

**Comment by LucaCinquini** [comment]
Thanks for the corrections, closing.
