### ISSUE TITLE
VnV-03: opera-sds/repositories landing page supposed to open source

### ISSUE THREAD

**Issue by oddes** [nasa/opera-sds-int#27]
Steps to Reproduce:
Open page: https://github.com/orgs/nasa/teams/opera-sds/repositories
you will notice this page requires login & does not show public:

Expected Result: Landing page need to be open sourced and does not require login to access the repositories: Please see the following link for the test results:

https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3989253&group_by=cases:title&group_order=asc&group_id=-1

**Comment by riverma** [comment]
@oddes - the expected link to list public repositories for OPERA that you want to use is: [https://github.com/nasa/?q=opera-](https://github.com/nasa/?q=opera-) 

I think you can close this ticket with the alternate above link.

**Comment by oddes** [comment]
Thanks.
