### ISSUE TITLE
Run 3 failed granules from R2 RC9 testing and additional list of granules of edge cases, no static_layer

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-int#33]
Edge Case Test List
R2-RC9: (3 granules) that failed.  Retest to make sure these passes.
Additional List of granules of edge cases (high latitude, anti-meridian) to be provided (Steven/Rosanna).

**NO static layer products for these**

Make sure to set **ASG max of cnn send job queue to be 0**. ASF is not yet ready to receive our products.

Use the following script to trigger jobs using text file list of granules:
https://github.com/nasa/opera-sds-ops/blob/r2-accountability/trigger_from_list.sh

**Comment by rsumagay** [comment]
Query from EARTHDATA : https://search.earthdata.nasa.gov/search
Collections:
  SENTINEL-1A_SLC
  SENTINEL-1B_SLC
  
Temporal Range: 07-01-2021 to 07-31-2021

Spatial Range: 
  **North Latitude Bounding Box**
  SW: 80, -179.8
  NE: 90, -179.9
  **South Latitude Bounding Box**
  SW: -90, -179.8
  NE: -76, -179.9
  
See ATTACHED Granule IDs
  
[S1A_SLC_SouthLatitude.txt](https://github.com/nasa/opera-sds-int/files/12364813/S1A_SLC_SouthLatitude.txt)
[S1B_SLC_SouthLatitude.txt](https://github.com/nasa/opera-sds-int/files/12364814/S1B_SLC_SouthLatitude.txt)
[S1B_SLC_NorthLatitude.txt](https://github.com/nasa/opera-sds-int/files/12364815/S1B_SLC_NorthLatitude.txt)
[S1A_SLC_NorthLatitude.txt](https://github.com/nasa/opera-sds-int/files/12364816/S1A_SLC_NorthLatitude.txt)

**Comment by rsumagay** [comment]
Spatial Range: 
  **Anti-Meridien Bounding Box**
  SW: -89, -179.9
  NE: 89, -179.8
  
  See Attached Granule IDs
  
  
[S1B_AntiMeridien.txt](https://github.com/nasa/opera-sds-int/files/12364892/S1B_AntiMeridien.txt)
[S1A_AntiMeridien.txt](https://github.com/nasa/opera-sds-int/files/12364893/S1A_AntiMeridien.txt)

**Comment by rsumagay** [comment]
Per TOAN:
From R2-RC9
S1A_IW_SLC__1SDH_20230722T122529_20230722T122548_049536_05F4DA_7EA8
S1A_IW_SLC__1SDH_20230722T122529_20230722T122548_049536_05F4DA_7EA8 (Duplicated)
S1A_IW_SLC__1SDH_20230722T122654_20230722T122724_049536_05F4DC_D8FF

From R2-RC8.
S1A_IW_SLC__1SDH_20230628T122459_20230628T122529_049186_05EA1E_AD77
S1A_IW_SLC__1SDH_20230628T122527_20230628T122546_049186_05EA1E_4B0C
S1A_IW_SLC__1SDH_20230628T122652_20230628T122722_049186_05EA20_0BC9

**Comment by philipjyoon** [comment]
The 5 granules that failed in rc8 and 9 have been submitted for processing. Will take about two hours.

Because the edge-case granules are much larger, I want to wait until at least the smoke test is successful before submitting those. So will submit those mid-afternoon today.

**Comment by philipjyoon** [comment]
Smoke test passed. Commencing edge cases.

**Comment by philipjyoon** [comment]
29 RTC jobs failed.
