### ISSUE TITLE
Create smoke test gold files for R2 RC10

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-int#36]

**Comment by collinss-jpl** [comment]
Assets for RC10 are available here:
CSLC-S1

- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/cslc_compare_results_calval_0.4.0.sh
- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/validate_cslc_product_calval_0.4.0.py
- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/deployment_smoke_test_cslc_s1_calval_0.4.0.zip

RTC-S1

- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/rtc_compare_calval_0.4.1.py
- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/rtc_compare_results_calval_0.4.1.sh
- https://artifactory-fn.jpl.nasa.gov/ui/repos/tree/General/general-stage/gov/nasa/jpl/opera/sds/pcm/testdata_R2.0.0/deployment_smoke_test_rtc_s1_calval_0.4.1.zip
