### ISSUE TITLE
OPERA-SDSVnV-6: Verify deployment of the SDS system to multiple AWS environments ("venues").

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#4]
Verify that the SDS software stack can be deployed and operated in multiple AWS environments (aka "venues"): DEV for developers, I&T for Integration and Testing, CalVal for product validation, and OPS for operations. 

TestRail link: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3718320&group_by=cases:section_id&group_order=asc&group_id=69570

**Comment by LucaCinquini** [comment]
o Add several other things that should be checked to verify a complete deployment, for example:
- S3 buckets
- Lambda functions
- Other UIs, including RabbitMQ and Elasticsearch
- AMIs
- ASGs

o Specify the URls to check, in the form http://<base DEV or InT or OPS URL>/path

**Comment by LucaCinquini** [comment]
Write one single set of instructions for DEV, I&T and OPS.

**Comment by oddes** [comment]
Luca,

Please review this:
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3718320

**Comment by oddes** [comment]
I am not sure why do we test for DEV environment or OPS environment, not sure do we have even access to it.

**Comment by LucaCinquini** [comment]
Good point - maybe the operators need to be in charge of verifying this ticket for the Ops system? And the developers for the Dev system?
BTW - as it currently stands - step #11 needs to be in bold face since it's a section.

**Comment by oddes** [comment]
Hi Luca,
Updated step 11.

**Comment by LucaCinquini** [comment]
Let's add that different people, with the correct permissions, will be responsible for verifying the deployment to DEV, PST and OPS.

**Comment by riverma** [comment]
Hi Folks - since these TestRail ticket URLs are inaccessible in public GitHub, I suggest we work out the general _content_ here for the test case, and leave the links out. It's more clear / useful for everyone that way. If the tests have scripts, we should version control them here. Thanks!

**Comment by oddes** [comment]
Luca, I have updated all the steps needed, please review and close this ticket

**Comment by LucaCinquini** [comment]
The description of the current tests looks good to me. A few things to do:
o Rename the Testrail plan form ..VnV-6_1 to VnV-6 (since there is one Testrail plan for this item)
o At the end of the InT steps, add one or more steps to verify that the smoke tests for that deployment were successful (talk to Chris if needed)

**Comment by oddes** [comment]
Luca, Added both the points to the test.
