### ISSUE TITLE
OPERA-SDSVnV-16: Verify archival of DSWX_HLS data products

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#5]
L3 Requirement:
Verify that the standard data products are available to designated DAACS as defined in ICD. Use the CMR query service to locate the products of interest, and Cumulus data services to download the data.Execute these tests for each OPERA data products, and for multiple time intervals and geographic selections.

Verify that the SDS adheres to the external interfaces with the DAACs as specified in the ICD agreement, specifically:
o The SDS uses CNM ("Cloud Notification Mechanism") to notify the target DAAC that new output prodcuts are available for archiving

Verify that the DAAC metadata is delivered to the DAAC with the product.

TestRail case: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3678197&group_by=cases:section_id&group_order=asc&group_id=69570

**Comment by LucaCinquini** [comment]
Note that Step 1 (verify that .netrc file exists) will have to change when files are downloaded not through HTTPS, but rather via direct S3 access.

**Comment by LucaCinquini** [comment]
Step 8: add the LP.DAAC URL
Step 9:
- describe how to query for HLSS30 data (which web controls to use)
- add query for HLSL30?

**Comment by LucaCinquini** [comment]
Can we do this test without running the PGE? By simply moving an output products to the location where it will trigger a CNM?
Let's test everything we can first without DAAC intervention, then let's involve the DAACs.

**Comment by hhlee445** [comment]
This can be done by staging L3_DSWX_HLS products into the ISL bucket.

**Comment by LucaCinquini** [comment]
We decided to proceed as follow:
- get hold of the output files from the previous PGE run (see another test case)
- move those files to the correct output directory in the ISL bucket
- that should trigger the CNM message to the DAAC - use the UI to verify the job is submitted
- when the job completes, use the CMR query to verify that the output products have been ingested (including their metadata)

**Comment by LucaCinquini** [comment]
Must use the test collection at the DAAC to verify that the products are ingested (not the final operational collection).

**Comment by LucaCinquini** [comment]
Please add the following steps at the end:
o Use CMR query to locate the DSWx products at the PO.DAAC
o Use the PO.DAAC Cumulus service to download the products

**Comment by oddes** [comment]
Updated:https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3678197

**Comment by oddes** [comment]
Updated: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3678197

**Comment by LucaCinquini** [comment]
Thanks for the update. I am ok with closing this ticket if Steven agrees as well.

**Comment by LucaCinquini** [comment]
We agreed the ticket is ok for now, closing.
