### ISSUE TITLE
OPERA-SDSVnV-3: Verify the SDS software is Open Source

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#6]
L3 Requirement:
Verify that the SDS software repositories are hosted on the public GitHub, and that other tools (forums, tickets, etc.) are available for Open Source development.
TestRail case: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/3551351&group_by=cases:section_id&group_order=asc&group_id=69570

**Comment by LucaCinquini** [comment]
Go to Github, verify repositories are there... list the repos...

**Comment by LucaCinquini** [comment]
Check there is an Open Source license.

**Comment by oddes** [comment]
Luca, Please review and Close.

**Comment by LucaCinquini** [comment]
Step 3: add "...for each repository."

**Comment by LucaCinquini** [comment]
Looks good, thanks.
