### ISSUE TITLE
OPERA-SDS-VnV-14: Verify archival of DSWX_HLS data product documentation

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-int#9]
Requirement: "Verify that all relevant information for the DSWX_HLS data product (description of science algorithm, validation datasets, test results, etc.) is available from the same DAAC where the data products are archived."

To Do:
o Define list of all documents that need to be archived at the DAACs- the DAAC that will host the data products
- product spec
- ATBD (Algorithm Theoretical Basis Document)
- SAS design?
- ICS?
o Determine where the DAACs store these documents (look at existing missions)

**Comment by oddes** [comment]
Luca,

working on it:  need to check if i miss any other documents.
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/cases/view/1101861

**Comment by LucaCinquini** [comment]
I suggest we keep this ticket open until we have more information on where each DAAC will store the documents. Apparently, DAACs will create a landing page for each collection, from where the documents can be retrieved. The locations of these web pages is still unknown.

**Comment by sjlewis-jpl** [comment]
The steps in Testrail are incomplete, and should say what is being verifyied about each document.  The actual requirement just requires us to make the information available to the DAACs, so perhaps we should just verify that the DAAC acknowledged receipt of the documents.

**Comment by LucaCinquini** [comment]
Sri to be more specific about how to verify the documents are there (i.e. go to the DAAC home page etc. etc.)

**Comment by oddes** [comment]
Luca, Please review updated test case and close it.

**Comment by LucaCinquini** [comment]
o Remove steps 6-10 since they don't pertain to DSWX_HLS
o For each of the steps 2-5 add: "<the document> is available for download".

**Comment by LucaCinquini** [comment]
Line 2 Expected Result:  The tester is able to download the product spec document.

**Comment by oddes** [comment]
Luca, updated as suggested.

**Comment by LucaCinquini** [comment]
+1 from me. Steven?

**Comment by LucaCinquini** [comment]
Steven concurs, closing
